on: 
    workflow_call:
        inputs:
            project-name:
                required: true
                type: string
            board-path:
                description: 'Path to kicad project in reference to root directory'
                required: false
                type: string
                default: './board'

jobs:
  Kicad-Generate-All:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Paths
      if: ${{github.event.inputs.board-path}} != ''
      run: echo ${{ github.event.client_payload.board-path }}

    
    - name: Run KiCad actions
      uses: actions-for-kicad/kicad-actions@v1.4-k9.0.2
      with:
        schematic_file_name: ${{inputs.board-path}}/${{inputs.project-name}}.kicad_sch
        symbol_libraries: "${{inputs.project-name}}=../lib/Symbols/${{inputs.project-name}}.kicad_sym"
        run_erc: false
        schematic_output_pdf: true
        schematic_output_bom: true
        pcb_output_step: true
        schematic_output_bom_fields: '*'
        schematic_output_bom_labels: Reference,Qty,Value,Exclude from BOM,Exclude from Board,Footprint,Datasheet
  
        pcb_file_name: ${{inputs.board-path}}/${{inputs.project-name}}.kicad_pcb
        footprint_libraries: "${{inputs.project-name}}=../lib/Footprints/${{inputs.project-name}}.pretty"
        run_drc: false
        pcb_output_gerbers_and_drill: true
        pcb_output_image: true
        pcb_output_step_file_name: ${{inputs.project-name}}.step

    - name: Upload schematic
      uses: actions/upload-artifact@v4
      with:
        name: Schematic
        path: ./schematic.pdf

    - name: Upload BOM
      uses: actions/upload-artifact@v4
      with:
        name: BOM
        path: ./bom.csv

    - name: Upload gerbers and drill file
      uses: actions/upload-artifact@v4
      with:
        name: Gerbers
        path: ./gerbers

    - name: Upload image render
      uses: actions/upload-artifact@v4
      with:
        name: Image render
        path: ./pcb.png

    - name: Upload step file
      uses: actions/upload-artifact@v4
      with:
        name: STEP
        path: ./${{inputs.project-name}}.step